version: "3"

services:
  web:
    build: .
    volumes:
      - ./main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt
      - ./input_images:/app/input_images
      - ./output_pdfs:/app/output_pdfs
    command: python main.py
